### ISSUE TITLE
where apollo3g_duo precompile

### ISSUE THREAD

**Issue by VishovVladimir** [ewaldc/My-Book-Live#16]
Hi, where can I get Apollo3g for Duo? There is no such thing in precompiled files

**Comment by ewaldc** [comment]
Hello Vladimir,
All kernels are compiled for both the regular and duo MBL (basically they all contain PCI-bus - for second sata - and USB support).
The one thing missing in the pre-compiled kernel zips is a pre-compiled device tree file for the duo.
[Here ](https://github.com/ewaldc/My-Book-Live/tree/master/kernel/dts) you can find the apollo3g dtd file for the duo.
They should work for any kernel 4.9.   The problem is that I don't have a duo, so I always need a volunteer that can check things for me.  For 4.19, I need to check.  I might have to compile a special one....

**Comment by VishovVladimir** [comment]
I can install a test version of the firmware on my MBL Duo. 
And another question, the firmware must be uploaded to disk A or to both HDD?

**Comment by VishovVladimir** [comment]
There are footprints for a fan connector on the motherboard of the device. Apparently, the developers initially thought to make active cooling, but changed their minds. Did you find the ability to control it in the firmware?

**Comment by ewaldc** [comment]
> And another question, the firmware must be uploaded to disk A or to both HDD?

It seems to me that all options for the single MBL apply, plus many new ones, but since I don't have a DUO I can't validate them.
For a single MBL, you can make any combination of :
- boot from a single disk (single partition, Linux software mirrored partition on same drive)
- boot from TFTP/BOOTP
- boot form NFS

With the DUO, you now add a second disk and you can create a software mirror over both disks (in JBOD mode).
Of course, that is for the logical side of things.  If you configure the DUO in RAID 0+1, than a single boot partition will be physically distributed over the two drives.   It might even be possible to enable boot over USB, but it might require modifying UBOOT (which I have done but given the high risk I have not made that public)

> There are footprints for a fan connector on the motherboard of the device

Are these also on regular MBL (picture?) ?   If it's properly connected, it might be possible. Toughest part would be the device tree piece (where is the status register). The kernel piece would be easy :  there is a very good generic PWM-driver with sysfs support. 

I tried to enable USB on the MBL and while I eventually succeeded to make it work it was not worth the ffort/risk: it required fine soldering on the motherboard, desoldering an SMD, emulating the crystal/internal clock by using the AMCC powerpc chip to generate the USB clock etc. 

Can you not power a fan from the USB connector or 12V input ? Should even be possible to include a USB hub board and power it off the 12V power supply. 

On my MBL I don't have cooling issues.  he only use case where my drive was heating up was in summer doing a lot of video streaming, but I found that a hybrid drive with a large cache and my network kernel tuning reduced the load the on the drive so much that is always ran "cool"

**Comment by VishovVladimir** [comment]
I took the image from https://github.com/ewaldc/My-Book-Live/blob/master/debian/debian%208%20(Jessie)/DebianJessie8.11.tgz.url.
unpacked it into section SDA1. copied apollo3g_duo.dtb to apollo3g.dtb on /boot, and renamed it to /boot uImage_4.9.99 to uImage. But in this case, the system does not start
By UART it have this:
```
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
CPU: 0 PID: 1 Comm: swapper Not tainted 4.9.99-mbl+ #1
Call Trace:
[cf991e30] [c041917c] 0xc041917c (unreliable)
[cf991e90] [c04e0e70] 0xc04e0e70
[cf991ee0] [c04e11d0] 0xc04e11d0
[cf991f00] [c04e0a84] 0xc04e0a84
[cf991f30] [c0001b7c] 0xc0001b7c
[cf991f40] [c000ac10] 0xc000ac10
Rebooting in 180 seconds..
```

**Comment by ewaldc** [comment]
Some things to check....
There is the notion of boot and root (debian Linux) partition, either as separate or combined partition(s).  For boot, only ext2/3 are supported (U-boot restriction). For root, ext2/3/4 are supported.
Boot and root can be together on a single filesystem or separate (a disk volume with just /boot).

If your root partition is on ext4, you need to specify this in the kernel command line as in https://github.com/ewaldc/My-Book-Live/blob/master/uboot/boot_ext4_sda1/boot_ext4_sda1.txt.
If your /boot is combined with root, you have to reformat it as ext3.

This is explained on the page https://github.com/ewaldc/My-Book-Live/tree/master/debian/debian%208%20(Jessie)

For both boot and root there is the concept of mounting "/" (root), so the error could be due to /boot being on ext4 or /root on ext4 without proper kernel command line.

Hope this helps

**Comment by JFranko21** [comment]
I would love to try the 4.19 kernel on MBL Duo, is it possible to get any sources or file for a test from you?

**Comment by JFranko21** [comment]
Also there is a kernel 5.10 from openWRT, do you think it will work OOTB with your Debian?

**Comment by ewaldgh** [comment]
Sorry for late response.  Kernel source is available in the form of a series of patches, For kernel 4.19 you will find them [here](https://github.com/ewaldc/My-Book-Live/tree/master/kernel/patches/4.19).  It is very unlikely the openWRT 5.10 kernel will work out of the box.   I do not recommend to use 5.x kernels as performance has significantly decreased.   When I still had my development WDL I tried to tune 5.4 to come within 10% of 4.x kernels, but ended up patching the tcp/ip and ATA stacks in so many places that I was becoming a true Linux kernel maintainer.   The problem is that new hardware is so much faster than before, that kernel developers are focused on getting functionality released rather than tuning the current functionality.
Part of the performance drop is also due to the large size increase and extra memory consumption which is not helpful if you have only 256MB of memory.
Also, there are almost no functions in 5.x that our HW can leverage that are not in 4.9 or 4.19.    The openwrt team is seeing the same issues and they do recommend to use OpeWRT 17.x on older devices for that exact reason.

**Comment by VishovVladimir** [comment]
Hello! I come back) I trying  fix my MBL DUO again. I have a problem, I start with one HDD in slot A, it start correctly, if i plugin second HDD in hot, MBL finds hard disc corect. But if I reboot device and it trying boot with two disk I have boot fail.
I try clone disks with same version of firmware on both 
but it don't work
On UART Console there are : 
```
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(8,1)
CPU: 0 PID: 1 Comm: swapper Not tainted 4.9.99-mbl+ #1
Call Trace:
[cf991e30] [c041917c] 0xc041917c (unreliable)
[cf991e90] [c04e0e70] 0xc04e0e70
[cf991ee0] [c04e11d0] 0xc04e11d0
[cf991f00] [c04e0a84] 0xc04e0a84
[cf991f30] [c0001b7c] 0xc0001b7c
[cf991f40] [c000ac10] 0xc000ac10
```
