### ISSUE TITLE
how to install Debian Jessie on My-Book-Live ?

### ISSUE THREAD

**Issue by BackT0TheFuture** [ewaldc/My-Book-Live#19]
@ewald- 
Hi, it's great to find this repo
I have one my book live 3TB
It's slow but working
how to install your image?
thanks!

**Comment by ewaldc** [comment]
Take a look: [here](https://github.com/ewaldc/My-Book-Live/tree/master/debian/debian%208%20(Jessie)).
It does require a Linux system though.  Let me know if that does not work for you.

**Comment by BackT0TheFuture** [comment]
@ewaldc 

thanks for your reply!
I'ver read it , but I'm still a little confused. 

1. the kernel version of my book live is **2.6.32.11** , should I upgrade it to **2.6.32.70** firstly before other actions?

`
Linux Cloud 2.6.32.11-svn70860 #1 Thu May 17 13:32:51 PDT 2012 ppc GNU/Linux
`

2.  does compressed tar [image](https://drive.google.com/open?id=1eCr4pyYLKAHId2QINgrGdd9GWCsWVGQG) include safe/recovery kernels or u-boot ?

3. If the image does not include safe/recovery kernels or u-boot, should I install it firstly?

**Comment by ewaldc** [comment]
Understood, there are indeed (too) many options to choose from and it's easy to get lost

1. On the exsting MBL software you can (only) install my performance tuned kernel 2.6.32.70 (and .71).  This will bring the support level to the latest. most stable, 2.x series kernel and will provide enhanced performance.  In this case you end up with  Debian Lenny (the original, from WD), the WD web interface and a more recent, faster kernel.  Performance-wise, this combination is the best, but you are left with a vulnerable and old OS that has been hacked many times, leaving folks with a wiped, "factory reset" drive.

2. You can replace the orginal Debian 5.0 aka "Lenny", with Debian 8.11 aka. Jessie, released mid 2018. Jessie benefits from Long Term Support (LTS), but that support ended in June 2020.  Included with my Debian image comes a 4.9.x kernel.   In prinicple this image includes everything you need, but there are a few files that need your attention as described in the installation notes.   This gives you a fairly recent OS and modern 4.x kernel with performance that matches and often exceeds the original MBL and one significant advantage: you can use a regular filesystem block size so that you can mount your MBL disk on a regular Linux machine (not the case with the 64K block size of WD).  On the downside, you lose the WD web interface and "reset" button.

3. Once you are on Debian 8.11, you can further experiment with other kernels (e.g. 4.19), netconsole (u-boot section), network booting, recovery kernels etc., and you can even build your own kernel.  That is the more advanced stuff...
4.  Since Debian 8.11 is no longer supported now and Debian ended support for the PowerPC-32 architecture, there is now a new project based on Debian "Unstable".  You can read about it [here](https://github.com/ewaldc/mbl-debian).  However, I still need to provide a performance tuned version for this new Debian release.

Whichever option you choose, make sure you have a good backup!

**Comment by bdutzz** [comment]
hi @ewaldc sorry for hijacking the topic, 

however it's related to installation, so i'll just ask here instead of opening new ticket,

i have challenge in installing separate /boot and / partition, as following:
sda1 ext3 as /boot 
sda2 ext4 as / 

i followed your installation instruction
1. tar xzf DebianJessie8.11.tgz to sda2
2. cp -rp boot/* to sda1, rm -rf boot/* in sda2
3. changed boot.scr using boot_ext4_sda1 (see below, not sure if this is intended but for some reason ext4 is switched between name & content)
https://github.com/ewaldc/My-Book-Live/tree/master/uboot/boot_ext3_sda1 (root=/dev/sda1)
https://github.com/ewaldc/My-Book-Live/tree/master/uboot/boot_ext3_sda2 (root=/dev/sda2)
https://github.com/ewaldc/My-Book-Live/tree/master/uboot/boot_ext4_sda1 (root=/dev/sda2)
https://github.com/ewaldc/My-Book-Live/tree/master/uboot/boot_ext4_sda2 (root=/dev/sda1)
4. patched with https://github.com/ewaldc/My-Book-Live/blob/master/kernel/precompiled/kernel.4.19.99.tar lib goes to sda2, boot goes to sda1, cp uImage_4.19.99+x to uImage
5. changed fstab to following
tmpfs
sda2 / ext4
sda1 /boot ext3

but it failed to boot, have been trying to work on this for few days to no result

**Comment by ewaldc** [comment]
Hello,
It is a recommended best practice to open a new issue for a new question...

"_Not sure if this is intended but for some reason ext4 is switched between name & content_".
The name "boot_ext4_sda1"  refers to the fact that /boot is on sda1 with / (root) being a ext4 filesystem.  The text ("root=/dev/sda2") besides it refers to the fact that / (aka the root filesystem) is on sda2.  
I know this isn't the easiest of things, unfortunately...

What you mention seems all fine to me.   
One thing to keep in mind though is the link between kernel page size and swap space/disk block size.

If using swap, what page size have you used for swap ?  Has the swap space been allocated accordingly ?  See the last paragraph [here](https://github.com/ewaldc/My-Book-Live/tree/master/kernel/precompiled): the 4.19 precompiled kernels use a 16K page size, so the proper command to initialize swap space is: mkswap --pagesize 16384 /dev/sda3.  One possibility is to take swap out of /etc/fstab initially. 

Accordingly, you must have a compatible disk block size for both / and / boot, e.g. for 16K kernel page size: 4K or 16K block size are OK, but not 64K (which requires a kernel with 64K page size)

Other than that, it is probably the easiest to start with everything on ext3 on sda1 (less things that can go wrong) and the initial kernel from the Debian image.  From there you can always optimize/tune or improve.
If everything fails, is there anyway for you enable netconsole so you can see the boot process ?  

Hope this helps.

**Comment by id222id** [comment]
Hello!
What about Debian 12? Can you help us please...

**Comment by ewaldc** [comment]
Sorry for late reply. Take a look [here](https://github.com/ewaldc/mbl-debian).
At the moment, the optimized MBL kernel only exists for LTS 5.4, but you can run the latest 6.4. and 6.5 kernels if desired.

**Comment by ewaldc** [comment]
For those struggling to get the old Debian Jessie going there is the new Debian Unstable installer which supports Debian 12.
See [mbl-debian](https://github.com/ewaldc/mbl-debian)
