### ISSUE TITLE
scp speed is very slow

### ISSUE THREAD

**Issue by ihanbing** [ewaldc/My-Book-Live#6]
Hi, Ewaldc,
after I install your custom rom into MBL, scp is very slow from my PC. Both of them are 1000m ethernet connection, can you help on this?
1987.iso                                        7%  464MB   7.9MB/s   11:47 ETA

Thanks a lot

**Comment by ihanbing** [comment]
The performance is limited by CPU, which has almost full usage. Maybe the hardware encryption acceleration and ethernet/sata dma are not enabled in my device.

**Comment by ewaldc** [comment]
Today I am on assignment abroad, but will check SCP speed as I get home late on Friday.  Since the MBL can receive data at 122MB/s over ethernet using the modified network drivers, it is likely that the writing to disk and encryption are the reasons for things to slow down.  With Samba I get 80MB/s write, so most likely it's the encryption.   Hardware encryption is enabled as well as the user space crypto API , but I would need to compile a SCP/SFTP/SSH server that leverages this acceleration.   The standard PowerPC Debian Jessie Linux I use/posted does not have this acceleration built in.   Is there a way for you to copy over NFS, Samba or regular FTP ?

**Comment by ihanbing** [comment]
Hi, Ewaldc,
thanks for your reply. I think this issue can be closed. I can use other transfer methods instead of scp. I would have thought the root cause was emac driver.
